const Constants = {
    PAGE_LOADED: 'CABINET_PAGE_LOADED',
    PAGE_UNLOADED: 'CABINET_PAGE_UNLOADED',

    FETCH_ITEMS_REQUESTED: 'CABINET_FETCH_ITEMS_REQUESTED',
    FETCH_ITEMS_SUCCESSED: 'CABINET_FETCH_ITEMS_SUCCESSED',
    FETCH_ITEMS_FAILED: 'FETCH_ITEMS_FAILED',

    CHANGE_FORM: 'CABINET_CHANGE_FORM',

};

export default Constants;
