const Constants = {
    PAGE_LOADED: '404_PAGE_LOADED',
    PAGE_UNLOADED: '404_PAGE_UNLOADED',

    FETCH_ITEMS_REQUESTED: '404_FETCH_ITEMS_REQUESTED',
    FETCH_ITEMS_SUCCESSED: '404_FETCH_ITEMS_SUCCESSED',
    FETCH_ITEMS_FAILED: 'FETCH_ITEMS_FAILED',
};

export default Constants;
