const Constants = {
    PAGE_LOADED: 'LOGIN_PAGE_LOADED',
    PAGE_UNLOADED: 'LOGIN_PAGE_UNLOADED',

    FETCH_ITEMS_REQUESTED: 'LOGIN_FETCH_ITEMS_REQUESTED',
    FETCH_ITEMS_SUCCESSED: 'LOGIN_FETCH_ITEMS_SUCCESSED',
    FETCH_ITEMS_FAILED: 'FETCH_ITEMS_FAILED',

    CHANGE_FORM: 'LOGIN_CHANGE_FORM',
};

export default Constants;
